CREATE TABLE otps
(
    user_id    BIGINT NOT NULL,
    type       VARCHAR(255),
    value      VARCHAR(255),
    issued_at  BIGINT,
    expires_at BIGINT,
    CONSTRAINT pk_otps PRIMARY KEY (user_id)
);

ALTER TABLE attachments
    ADD user_id BIGINT;

ALTER TABLE attachments
    ADD uuid VARCHAR(255);

ALTER TABLE attachments
    ALTER COLUMN user_id SET NOT NULL;

CREATE INDEX idx_attachment_user_id ON attachments (id, user_id);

CREATE UNIQUE INDEX idx_otp_value ON otps (value);

ALTER TABLE attachments
    ADD CONSTRAINT FK_ATTACHMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

DROP TABLE codes CASCADE;

ALTER TABLE messages
    DROP COLUMN attachments;

ALTER TABLE attachments
    DROP COLUMN id;

ALTER TABLE attachments
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

CREATE SEQUENCE IF NOT EXISTS attachments_id_seq;
ALTER TABLE attachments
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE attachments
    ALTER COLUMN id SET DEFAULT nextval('attachments_id_seq');

ALTER SEQUENCE attachments_id_seq OWNED BY attachments.id;