ALTER TABLE channels
    RENAME COLUMN icon_id TO avatar_id;

ALTER TABLE channels
    ADD CONSTRAINT FK_CHANNELS_ON_AVATAR FOREIGN KEY (avatar_id) REFERENCES attachments (id),
    DROP CONSTRAINT FK_CHANNELS_ON_ICON;

CREATE TABLE avatars
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    channel_id BIGINT                                  NOT NULL,
    uuid       VARCHAR(255),
    filename   VARCHAR(255),
    CONSTRAINT pk_avatars PRIMARY KEY (id)
);

ALTER TABLE avatars
    ADD CONSTRAINT FK_AVATARS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id),
    ADD CONSTRAINT FK_AVATARS_ON_CHANNEL FOREIGN KEY (channel_id) REFERENCES channels (id);
