CREATE TABLE attachments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    uuid    VARCHAR(255),
    filename     VARCHAR(255),
    content_type VARCHAR(255),
    flags        BIGINT,
    CONSTRAINT pk_attachments PRIMARY KEY (id)
);

CREATE TABLE channels
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    display_name VARCHAR(255),
    name         VARCHAR(255),
    icon BIGINT NOT NULL,
    type         INTEGER,
    flags        BIGINT,
    user_id      BIGINT                                  NOT NULL,
    created_at   BIGINT,
    CONSTRAINT pk_channels PRIMARY KEY (id)
);

CREATE TABLE members
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    permissions BIGINT,
    user_id     BIGINT                                  NOT NULL,
    channel     BIGINT                                  NOT NULL,
    joined_at   BIGINT,
    CONSTRAINT pk_members PRIMARY KEY (id)
);

CREATE TABLE messages
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content   TEXT,
    author    BIGINT                                  NOT NULL,
    timestamp BIGINT,
    channel   BIGINT                                  NOT NULL,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);

CREATE TABLE otps
(
    user_id    BIGINT NOT NULL,
    type       VARCHAR(255),
    value      VARCHAR(255),
    issued_at  BIGINT,
    expires_at BIGINT,
    CONSTRAINT pk_otps PRIMARY KEY (user_id)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    display_name VARCHAR(255),
    username     VARCHAR(255),
    email        VARCHAR(255),
    password     VARCHAR(255),
    avatar BIGINT NOT NULL,
    flags        BIGINT,
    type         INTEGER,
    created_at   BIGINT,
    deletion     BIGINT,
    key          VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE INDEX idx_attachment_user_id ON attachments (id, user_id);

CREATE UNIQUE INDEX idx_channel_name ON channels (name);

CREATE INDEX idx_member_user_channel ON members (user_id, channel);

CREATE INDEX idx_message_id_channel_id ON messages (id, channel);

CREATE UNIQUE INDEX idx_otp_value ON otps (value);

CREATE UNIQUE INDEX idx_user_email ON users (email);

CREATE UNIQUE INDEX idx_user_username ON users (username);

ALTER TABLE attachments
    ADD CONSTRAINT FK_ATTACHMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE channels
    ADD CONSTRAINT FK_CHANNELS_ON_ICON FOREIGN KEY (icon) REFERENCES attachments (id);

ALTER TABLE channels
    ADD CONSTRAINT FK_CHANNELS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE members
    ADD CONSTRAINT FK_MEMBERS_ON_CHANNEL FOREIGN KEY (channel) REFERENCES channels (id);

ALTER TABLE members
    ADD CONSTRAINT FK_MEMBERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_AUTHOR FOREIGN KEY (author) REFERENCES members (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_CHANNEL FOREIGN KEY (channel) REFERENCES channels (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_AVATAR FOREIGN KEY (avatar) REFERENCES attachments (id);