name: Update Docs

on:
  push:
    branches:
      - dev

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger endpoint
        run: |
          curl --request POST \
            --url https://api.mintlify.com/v1/project/update/${{ secrets.DOCS_PROJECT_ID }} \
            --header 'Authorization: Bearer ${{ secrets.DOCS_TOKEN }}'
